from django.urls import path
from . import views 

urlpatterns = [
     path("", views.management_portal, name="management_portal"),
     path("subtopics_for_topic/<int:topic_id>", views.subtopics_for_topic, name="subtopics_for_topic"),
     path("add_topic", views.add_topic, name="add_topic"),
     path("rename_topic", views.rename_topic, name="rename_topic"),
     path("get_topics", views.get_topics, name="get_topics"),
     path("delete_topic_form", views.delete_topic_form, name="delete_topic_form"),
     path("delete_topic/<int:topic_id>", views.delete_topic, name="delete_topic"),
     path("add_subtopic", views.add_subtopic, name="add_subtopic"),
     path("rename_subtopic", views.rename_subtopic, name="rename_subtopic"),
     path("delete_subtopic_form", views.delete_subtopic_form, name="delete_subtopic_form"),
     path("get_subtopics/<int:topic_id>", views.get_subtopics, name="get_subtopics"),
     path("get_subtopics_with_questions/<int:topic_id>", views.get_subtopics_with_questions, 
          name="get_subtopics_with_questions"),
     path("get_subtopics_with_questions_without_explanations/<int:topic_id>", 
          views.get_subtopics_with_questions_without_explanations, 
          name="get_subtopics_with_questions_without_explanations"),
     path("get_subtopics_with_questions_with_explanations/<int:topic_id>", 
          views.get_subtopics_with_questions_with_explanations, 
          name="get_subtopics_with_questions_with_explanations"),
     path("delete_subtopic/<int:subtopic_id>", views.delete_subtopic, name="delete_subtopic"),
     path("add_question_and_choices", views.add_question_and_choices, name="add_question_and_choices"),
     path("add_question_and_choices_dynamically", views.add_question_and_choices_dynamically, 
          name="add_question_and_choices_dynamically"),
     path("get_question_type_name/<int:pk>", views.get_question_type_name, name="get_question_type_name"),
     path("get_question_to_edit", views.get_question_to_edit, name="get_question_to_edit"),
     path("get_question_to_edit_dynamically", views.get_question_to_edit_dynamically, 
          name="get_question_to_edit_dynamically"),
     path("load_questions/<int:subtopic_id>", views.load_questions, name="load_questions"),
     path("get_all_questions_to_edit", views.get_all_questions_to_edit, name="get_all_questions_to_edit"),
     path("load_question_to_edit/<int:question_id>", views.load_question_to_edit, name="load_question_to_edit"),
     path("get_topic_name/<int:pk>", views.get_topic_name, name="get_topic_name"),
     path("get_subtopic_name/<int:pk>", views.get_subtopic_name, name="get_subtopic_name"),
     path("edit_question_and_choices", views.edit_question_and_choices, name="edit_question_and_choices"),
     path("edit_all_questions_and_choices", views.edit_all_questions_and_choices, 
          name="edit_all_questions_and_choices"),
     path("delete_question/<int:question_id>", views.delete_question, name="delete_question"),
     path("add_explanation", views.add_explanation, name="add_explanation"),
     path("edit_explanation", views.edit_explanation, name="edit_explanation"),
     path("load_questions_with_explanation/<int:subtopic_id>", views.load_questions_with_explanation,
          name="load_questions_with_explanation"),
     path("load_questions_without_explanation/<int:subtopic_id>", views.load_questions_without_explanation,
          name="load_questions_without_explanation"),
     path("get_explanation/<int:question_id>", views.get_explanation, name="get_explanation"),
     path("delete_explanation/<int:explanation_id>", views.delete_explanation, name="delete_explanation"),
     path("load_choices/<int:question_id>", views.load_choices, name="load_choices"),
]